# Generated by Django 5.2.10 on 2026-07-21 09:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Business or person the invoice is addressed to.', max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, help_text="City / region, e.g. 'Mbeya, Tanzania'.", max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, help_text='Auto-generated if left blank, e.g. KVS-2026-0001.', max_length=30, unique=True)),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('project_title', models.CharField(help_text="What this is for, e.g. 'Company Website — design, hosting & domain'.", max_length=255)),
                ('project_type', models.CharField(choices=[('website', 'Website'), ('system', 'System / Software'), ('poster', 'Poster / Design'), ('mobile_app', 'Mobile App'), ('maintenance', 'Maintenance / Support'), ('consultancy', 'Consultancy'), ('other', 'Other')], default='website', max_length=20)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, help_text='Optional. When full payment or the balance is expected.', null=True)),
                ('currency', models.CharField(default='TSh', max_length=8)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Optional discount applied to the subtotal.', max_digits=12)),
                ('deposit_percentage', models.PositiveIntegerField(default=75, help_text='Deposit expected up front (e.g. 75). Set 100 for full payment invoices.')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total the client has paid so far. Update as payments come in.', max_digits=12)),
                ('account_name', models.CharField(default='KianvoSoft', max_length=120)),
                ('bank_name', models.CharField(default='Selcom', max_length=120)),
                ('account_number', models.CharField(default='0753177709', max_length=60)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent — awaiting payment'), ('deposit_paid', 'Deposit paid'), ('partially_paid', 'Partially paid'), ('paid', 'Fully paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Shown to the client, e.g. terms or a thank-you note (Swahili is fine).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='invoices.client')),
            ],
            options={
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text="e.g. 'Website design & development', 'Domain (1 year)', 'Hosting (1 year)'.", max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('order', models.PositiveIntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
