# Generated by Django 5.2.10 on 2026-08-07 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='auto_renew',
            field=models.BooleanField(default=True, help_text='Subscription only. Tick if the plan continues after this period.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly (3 months)'), ('semi_annual', 'Half-yearly (6 months)'), ('annual', 'Yearly'), ('custom', 'Custom period')], default='monthly', help_text='Subscription only. How often this plan is billed.', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_type',
            field=models.CharField(choices=[('one_off', 'One-off project'), ('subscription', 'Subscription / recurring')], default='one_off', help_text='One-off for project work; Subscription for SaaS / recurring plans.', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='period_end',
            field=models.DateField(blank=True, help_text='Subscription only. Auto-filled from the cycle if left blank.', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='period_start',
            field=models.DateField(blank=True, help_text='Subscription only. First day of the period being billed.', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='plan_name',
            field=models.CharField(blank=True, help_text="Subscription only, e.g. 'Starter', 'Pro — 10 users'.", max_length=120),
        ),
        migrations.AddField(
            model_name='invoice',
            name='previous_invoice',
            field=models.ForeignKey(blank=True, help_text='Set automatically when an invoice is renewed for the next period.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='invoices.invoice'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='project_type',
            field=models.CharField(choices=[('website', 'Website'), ('system', 'System / Software'), ('saas', 'SaaS Subscription'), ('hosting', 'Hosting / Domain'), ('poster', 'Poster / Design'), ('mobile_app', 'Mobile App'), ('maintenance', 'Maintenance / Support'), ('consultancy', 'Consultancy'), ('other', 'Other')], default='website', max_length=20),
        ),
    ]
