# Generated by Django 5.2.10 on 2026-08-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_auto_renew_invoice_billing_cycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='renewal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='What the client pays NEXT time, if it differs from this invoice. Leave blank if the amount stays the same.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='renewal_date',
            field=models.DateField(blank=True, help_text='When that next payment is due. Subscriptions use the day after the period ends if left blank.', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='renewal_label',
            field=models.CharField(blank=True, help_text="What the next payment covers, e.g. 'Hosting, domain & support (1 year)'. Printed on the invoice.", max_length=200),
        ),
    ]
