# Generated by Django 5.2.10 on 2026-08-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_renewal_amount_invoice_renewal_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('subscription', 'Subscription band (plan & period)'), ('items', 'Line items table'), ('totals', 'Totals'), ('payment', 'Payment details / Malipo'), ('next_payment', 'Next payment notice'), ('notes', 'Notes to the client')], max_length=30, unique=True)),
                ('position', models.PositiveIntegerField(default=0, help_text='Lower numbers print first.')),
                ('visible', models.BooleanField(default=True, help_text='Untick to leave this block off every invoice.')),
            ],
            options={
                'verbose_name': 'Invoice layout block',
                'verbose_name_plural': 'Invoice layout',
                'ordering': ['position', 'id'],
            },
        ),
    ]
