# Generated by Django 5.2.10

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_seed_invoice_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, help_text='Auto-generated if left blank, e.g. KVS-RCT-2026-0001.', max_length=30, unique=True)),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount this receipt covers — this payment only, not the invoice total.', max_digits=12)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('payment_method', models.CharField(choices=[('mobile_money', 'Mobile Money (Selcom, M-Pesa, Tigo Pesa...)'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('card', 'Card'), ('cheque', 'Cheque'), ('other', 'Other')], default='mobile_money', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Transaction / confirmation code, e.g. the Selcom reference.', max_length=120)),
                ('received_by', models.CharField(blank=True, default='KianvoSoft', max_length=120)),
                ('balance_before', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Shown to the client, e.g. a thank-you note (Swahili is fine).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='invoices.invoice')),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
            },
        ),
    ]
