"""
Django settings for kianvosoft project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ---------------------------------------------------------------------------
# Environment detection
# ---------------------------------------------------------------------------
# Set DJANGO_ENV=production on cPanel (done in passenger_wsgi.py).
# Leave it unset locally and DEBUG stays True automatically.
_ENV = os.environ.get('DJANGO_ENV', 'development')
IS_PRODUCTION = (_ENV == 'production')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-y)@x+!u7k5xb3*tl$o*-@w&t4s!%%!!dz%699)r*pzxp(!533s'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not IS_PRODUCTION

ALLOWED_HOSTS = ['kianvosoft.com', 'www.kianvosoft.com', 'localhost', '127.0.0.1']

# ---------------------------------------------------------------------------
# Production-only security settings
# ---------------------------------------------------------------------------
if IS_PRODUCTION:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django.contrib.sites',
    'ckeditor',
    'ckeditor_uploader',
    'kianvosite',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kianvosoft.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'kianvosite.context_processors.global_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'kianvosoft.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
# STATIC_ROOT is where collectstatic copies files for production serving.
# On cPanel, run: python manage.py collectstatic --noinput
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Silence django-ckeditor's CKEditor 4 advisory (non-functional warning)
LOGIN_URL = '/portal/login/'
LOGIN_REDIRECT_URL = '/portal/dashboard/'
LOGOUT_REDIRECT_URL = '/portal/login/'

SILENCED_SYSTEM_CHECKS = ['ckeditor.W001']

SITE_URL = 'https://kianvosoft.com'

# Google Analytics Measurement ID (set in production)
GOOGLE_ANALYTICS_ID = ''

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.kianvosoft.com'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'info@kianvosoft.com'
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'Kianvo@2026')
DEFAULT_FROM_EMAIL = 'KianvoSoft <info@kianvosoft.com>'
SERVER_EMAIL = 'info@kianvosoft.com'
ADMINS = [('Admin', 'admin@kianvosoft.com')]

# CKEditor Configuration
CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_IMAGE_BACKEND = 'pillow'
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Format', 'Bold', 'Italic', 'Underline', 'Strike', '-', 'RemoveFormat'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote'],
            ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['Image', 'Table', 'HorizontalRule', 'SpecialChar'],
            ['Source'],
        ],
        'height': 500,
        'width': '100%',
        'removePlugins': 'elementspath',
        'resize_enabled': True,
        'format_tags': 'p;h2;h3;h4;pre',
    },
    # Blog post editor — full-featured for structured article writing
    'blog': {
        'skin': 'moono-lisa',
        'toolbar': 'BlogFull',
        'toolbar_BlogFull': [
            # Row 1: Format & text style
            {'name': 'format',     'items': ['Format']},
            {'name': 'basicstyle', 'items': ['Bold', 'Italic', 'Underline', 'Strike', '-', 'RemoveFormat']},
            {'name': 'color',      'items': ['TextColor', 'BGColor']},
            '/',
            # Row 2: Structure
            {'name': 'paragraph', 'items': [
                'NumberedList', 'BulletedList', '-',
                'Outdent', 'Indent', '-',
                'Blockquote', '-',
                'JustifyLeft', 'JustifyCenter', 'JustifyRight',
            ]},
            {'name': 'links',  'items': ['Link', 'Unlink']},
            {'name': 'insert', 'items': ['Image', 'Table', 'HorizontalRule']},
            {'name': 'tools',  'items': ['Source', '-', 'Maximize']},
        ],
        'height': 650,
        'width': '100%',
        'removePlugins': 'elementspath',
        # Only expose Paragraph, Heading 2, Heading 3, Heading 4, Preformatted
        'format_tags': 'p;h2;h3;h4;pre',
        'format_h2': {'element': 'h2', 'name': 'Section Heading (H2)'},
        'format_h3': {'element': 'h3', 'name': 'Sub-heading (H3)'},
        'format_h4': {'element': 'h4', 'name': 'Minor Heading (H4)'},
        'format_pre': {'element': 'pre', 'name': 'Code Block'},
        # Enter key creates <p>, Shift+Enter creates <br>
        'enterMode': 1,
        'shiftEnterMode': 2,
        # Allow the full set of HTML tags CKEditor outputs
        'allowedContent': True,
        'resize_enabled': True,
        'extraPlugins': 'maximize',
    },
}
