import datetime
import re
from decimal import Decimal

from django.test import TestCase
from django.urls import reverse

from .models import Client, Invoice, InvoiceItem, InvoiceSection
from .pdf import render_invoice_pdf


class InvoiceMoneyTests(TestCase):
    def setUp(self):
        self.client_obj = Client.objects.create(name='Test Client')
        self.inv = Invoice.objects.create(
            client=self.client_obj,
            project_title='Website',
            deposit_percentage=75,
        )
        InvoiceItem.objects.create(
            invoice=self.inv, description='Design & development',
            quantity=1, unit_price=Decimal('99000'),
        )
        InvoiceItem.objects.create(
            invoice=self.inv, description='Domain & hosting',
            quantity=1, unit_price=Decimal('50000'),
        )

    def test_number_autogenerated(self):
        self.assertTrue(self.inv.number.startswith('KVS-'))

    def test_totals(self):
        self.assertEqual(self.inv.subtotal, Decimal('149000.00'))
        self.assertEqual(self.inv.total, Decimal('149000.00'))
        self.assertEqual(self.inv.deposit_amount, Decimal('111750.00'))
        self.assertEqual(self.inv.balance_due, Decimal('149000.00'))

    def test_deposit_payment(self):
        self.inv.amount_paid = Decimal('111750')
        self.inv.save()
        self.assertEqual(self.inv.amount_outstanding_now, Decimal('0.00'))
        self.assertEqual(self.inv.balance_due, Decimal('37250.00'))
        self.assertFalse(self.inv.is_paid)

    def test_full_payment(self):
        self.inv.amount_paid = Decimal('149000')
        self.inv.save()
        self.assertTrue(self.inv.is_paid)


class SubscriptionInvoiceTests(TestCase):
    def setUp(self):
        self.client_obj = Client.objects.create(name='Shule Bora')
        self.sub = Invoice.objects.create(
            client=self.client_obj,
            project_title='School Management System',
            project_type='saas',
            billing_type=Invoice.BILLING_SUBSCRIPTION,
            billing_cycle=Invoice.CYCLE_MONTHLY,
            plan_name='Standard — 200 students',
            issue_date=datetime.date(2026, 1, 31),
            period_start=datetime.date(2026, 1, 31),
        )
        InvoiceItem.objects.create(
            invoice=self.sub, description='Monthly subscription',
            quantity=1, unit_price=Decimal('60000'),
        )

    def test_period_end_and_due_date_filled(self):
        # 31 Jan + 1 month clamps to 28 Feb, period ends the day before.
        self.assertEqual(self.sub.period_end, datetime.date(2026, 2, 27))
        self.assertEqual(self.sub.due_date, datetime.date(2026, 1, 31))

    def test_subscription_bills_in_full(self):
        self.assertEqual(self.sub.deposit_percentage, 100)
        self.assertEqual(self.sub.amount_outstanding_now, Decimal('60000.00'))

    def test_next_period_start(self):
        self.assertEqual(self.sub.next_period_start, datetime.date(2026, 2, 28))

    def test_renewal_clones_items_and_chains(self):
        renewal = self.sub.create_next_period_invoice()
        self.assertIsNotNone(renewal)
        self.assertEqual(renewal.period_start, datetime.date(2026, 2, 28))
        self.assertEqual(renewal.period_end, datetime.date(2026, 3, 27))
        self.assertEqual(renewal.previous_invoice, self.sub)
        self.assertEqual(renewal.status, Invoice.STATUS_DRAFT)
        self.assertEqual(renewal.amount_paid, Decimal('0.00'))
        self.assertEqual(renewal.total, Decimal('60000.00'))
        self.assertNotEqual(renewal.number, self.sub.number)

    def test_yearly_cycle(self):
        inv = Invoice.objects.create(
            client=self.client_obj, project_title='Hosting',
            billing_type=Invoice.BILLING_SUBSCRIPTION,
            billing_cycle=Invoice.CYCLE_ANNUAL,
            period_start=datetime.date(2026, 3, 1),
        )
        self.assertEqual(inv.period_end, datetime.date(2027, 2, 28))

    def test_no_renewal_when_auto_renew_off(self):
        self.sub.auto_renew = False
        self.sub.save()
        self.assertIsNone(self.sub.next_period_start)
        self.assertIsNone(self.sub.create_next_period_invoice())

    def test_price_change_replaces_lines_on_renewal(self):
        self.sub.renewal_amount = Decimal('75000')
        self.sub.renewal_label = 'Standard plan — new rate'
        self.sub.save()

        self.assertTrue(self.sub.has_price_change)
        self.assertEqual(self.sub.next_payment_amount, Decimal('75000.00'))

        renewal = self.sub.create_next_period_invoice()
        self.assertEqual(renewal.items.count(), 1)
        self.assertEqual(renewal.total, Decimal('75000.00'))
        self.assertEqual(renewal.items.first().description, 'Standard plan — new rate')
        # The new rate is now the standing price, so no further change is announced.
        self.assertFalse(renewal.has_price_change)

    def test_one_off_invoice_untouched(self):
        one_off = Invoice.objects.create(
            client=self.client_obj, project_title='Poster', deposit_percentage=75,
        )
        self.assertFalse(one_off.is_subscription)
        self.assertEqual(one_off.deposit_percentage, 75)
        self.assertIsNone(one_off.period_start)
        self.assertEqual(one_off.period_label, '')
        self.assertIsNone(one_off.next_period_start)
        self.assertFalse(one_off.has_price_change)


class FirstYearThenRenewalTests(TestCase):
    """Build the system now for one price; pay a different price from next year."""

    def setUp(self):
        self.client_obj = Client.objects.create(name='Duka la Mama')
        self.build = Invoice.objects.create(
            client=self.client_obj,
            project_title='POS System — build & first year',
            project_type='system',
            deposit_percentage=75,
            issue_date=datetime.date(2026, 8, 1),
            billing_cycle=Invoice.CYCLE_ANNUAL,
            renewal_amount=Decimal('250000'),
            renewal_date=datetime.date(2027, 8, 1),
            renewal_label='Hosting, domain & support (1 year)',
        )
        InvoiceItem.objects.create(
            invoice=self.build, description='System development',
            quantity=1, unit_price=Decimal('1200000'),
        )

    def test_notice_shows_on_a_one_off_invoice(self):
        self.assertFalse(self.build.is_subscription)
        self.assertEqual(self.build.total, Decimal('1200000.00'))
        self.assertEqual(self.build.next_period_start, datetime.date(2027, 8, 1))
        self.assertEqual(self.build.next_payment_amount, Decimal('250000.00'))
        self.assertTrue(self.build.has_price_change)
        self.assertEqual(self.build.renewal_covers, 'Hosting, domain & support (1 year)')

    def test_deposit_still_applies_to_the_build_invoice(self):
        self.assertEqual(self.build.deposit_percentage, 75)
        self.assertEqual(self.build.deposit_amount, Decimal('900000.00'))

    def test_renewal_bills_the_new_price_and_keeps_repeating(self):
        year_two = self.build.create_next_period_invoice()
        self.assertEqual(year_two.issue_date, datetime.date(2027, 8, 1))
        self.assertEqual(year_two.total, Decimal('250000.00'))
        self.assertEqual(year_two.items.count(), 1)
        self.assertEqual(
            year_two.items.first().description, 'Hosting, domain & support (1 year)',
        )
        # Year three is queued at the same rate.
        self.assertEqual(year_two.renewal_date, datetime.date(2028, 8, 1))
        self.assertFalse(year_two.has_price_change)

        year_three = year_two.create_next_period_invoice()
        self.assertEqual(year_three.issue_date, datetime.date(2028, 8, 1))
        self.assertEqual(year_three.total, Decimal('250000.00'))

    def test_discount_does_not_leak_into_the_new_price(self):
        self.build.discount = Decimal('200000')
        self.build.save()
        self.assertEqual(self.build.total, Decimal('1000000.00'))
        year_two = self.build.create_next_period_invoice()
        self.assertEqual(year_two.discount, Decimal('0.00'))
        self.assertEqual(year_two.total, Decimal('250000.00'))


class PdfTests(TestCase):
    """The PDF is built server-side so it has no browser headers, URLs or
    page numbering, and is always a single page."""

    def setUp(self):
        self.client_obj = Client.objects.create(name='JC Pharmacy', phone='0767297615')
        self.inv = Invoice.objects.create(
            client=self.client_obj, project_title='IMFORIA', project_type='saas',
            billing_type=Invoice.BILLING_SUBSCRIPTION, plan_name='Business Plan',
            billing_cycle=Invoice.CYCLE_ANNUAL,
            issue_date=datetime.date(2026, 8, 7),
            period_start=datetime.date(2026, 8, 7),
            discount=Decimal('118000'),
            renewal_amount=Decimal('649000'),
            renewal_label='System subscription — hosting, updates & support',
        )
        InvoiceItem.objects.create(
            invoice=self.inv, description='System subscription',
            quantity=1, unit_price=Decimal('708000'),
        )

    @staticmethod
    def _page_count(pdf_bytes):
        return len(re.findall(rb'/Type\s*/Page[^s]', pdf_bytes))

    def _add_items(self, count):
        for i in range(count):
            InvoiceItem.objects.create(
                invoice=self.inv, order=i + 1,
                description=f'Module {i + 1} — configuration, migration and testing',
                quantity=1, unit_price=Decimal('150000'),
            )

    def test_single_page(self):
        self.assertEqual(self._page_count(render_invoice_pdf(self.inv)), 1)

    def test_long_invoice_still_single_page(self):
        self._add_items(20)
        self.assertEqual(self._page_count(render_invoice_pdf(self.inv)), 1)

    def test_view_serves_pdf_inline_and_as_download(self):
        url = reverse('invoices:invoice_pdf', args=[self.inv.public_token])

        inline = self.client.get(url)
        self.assertEqual(inline.status_code, 200)
        self.assertEqual(inline['Content-Type'], 'application/pdf')
        self.assertTrue(inline['Content-Disposition'].startswith('inline'))
        self.assertTrue(inline.content.startswith(b'%PDF'))
        self.assertIn(self.inv.number, inline['Content-Disposition'])

        download = self.client.get(url + '?download=1')
        self.assertTrue(download['Content-Disposition'].startswith('attachment'))

    def test_unknown_token_is_404(self):
        url = reverse('invoices:invoice_pdf',
                      args=['00000000-0000-0000-0000-000000000000'])
        self.assertEqual(self.client.get(url).status_code, 404)


class LayoutOrderTests(TestCase):
    def setUp(self):
        self.client_obj = Client.objects.create(name='Layout Co')
        self.inv = Invoice.objects.create(
            client=self.client_obj, project_title='Website', notes='Asante sana',
        )
        InvoiceItem.objects.create(
            invoice=self.inv, description='Design', quantity=1,
            unit_price=Decimal('400000'),
        )

    def test_default_order_is_seeded_by_migration(self):
        self.assertEqual(InvoiceSection.ordered_keys(), InvoiceSection.DEFAULT_ORDER)

    def test_payment_comes_before_next_payment_by_default(self):
        keys = InvoiceSection.ordered_keys()
        self.assertLess(keys.index(InvoiceSection.PAYMENT),
                        keys.index(InvoiceSection.NEXT_PAYMENT))

    def test_admin_reorder_changes_the_public_page(self):
        InvoiceSection.objects.filter(key=InvoiceSection.NOTES).update(position=0)
        html = self.client.get(self.inv.get_absolute_url()).content.decode()
        self.assertLess(html.index('Notes'), html.index('Payment Details'))

    def test_hidden_block_disappears(self):
        InvoiceSection.objects.filter(key=InvoiceSection.NOTES).update(visible=False)
        self.assertNotIn(InvoiceSection.NOTES, InvoiceSection.ordered_keys())
        html = self.client.get(self.inv.get_absolute_url()).content.decode()
        self.assertNotIn('Asante sana', html)

    def test_empty_table_falls_back_to_the_default_order(self):
        InvoiceSection.objects.all().delete()
        self.assertEqual(InvoiceSection.ordered_keys(), InvoiceSection.DEFAULT_ORDER)
        self.assertEqual(self.client.get(self.inv.get_absolute_url()).status_code, 200)


class PaymentCallTests(TestCase):
    """The 'pay this now' bar: deposit first, then the remaining balance —
    never a stale zero once the deposit has landed."""

    def setUp(self):
        self.client_obj = Client.objects.create(name='Loyce Paul')
        self.inv = Invoice.objects.create(
            client=self.client_obj, project_title="Bloomer's Website",
            deposit_percentage=25, discount=Decimal('100000'),
        )
        InvoiceItem.objects.create(
            invoice=self.inv, description='Website',
            quantity=1, unit_price=Decimal('724000'),
        )

    def test_deposit_asked_for_before_anything_is_paid(self):
        call = self.inv.payment_call
        self.assertEqual(call['amount'], Decimal('156000.00'))
        self.assertIn('Deposit (25%)', call['label'])

    def test_switches_to_the_balance_once_the_deposit_is_covered(self):
        # 624,000 total; 468,000 (75%) paid; 156,000 still owed.
        self.inv.amount_paid = Decimal('468000')
        self.inv.save()
        self.assertEqual(self.inv.amount_outstanding_now, Decimal('0.00'))

        call = self.inv.payment_call
        self.assertEqual(call['amount'], Decimal('156000.00'))
        self.assertIn('Balance to complete', call['label'])
        self.assertNotIn('Deposit', call['label'])

    def test_partial_deposit_still_asks_for_the_rest_of_the_deposit(self):
        self.inv.amount_paid = Decimal('100000')
        self.inv.save()
        call = self.inv.payment_call
        self.assertEqual(call['amount'], Decimal('56000.00'))
        self.assertIn('Deposit (25%)', call['label'])

    def test_no_bar_once_fully_paid(self):
        self.inv.amount_paid = Decimal('624000')
        self.inv.save()
        self.assertIsNone(self.inv.payment_call)

    def test_bar_shows_on_the_public_page_with_the_balance(self):
        self.inv.amount_paid = Decimal('468000')
        self.inv.save()
        html = self.client.get(self.inv.get_absolute_url()).content.decode()
        self.assertIn('Balance to complete', html)
        self.assertIn('156,000', html)

    def test_pay_in_full_invoice_asks_for_the_whole_balance(self):
        full = Invoice.objects.create(
            client=self.client_obj, project_title='Poster', deposit_percentage=100,
        )
        InvoiceItem.objects.create(
            invoice=full, description='Poster', quantity=1, unit_price=Decimal('80000'),
        )
        self.assertEqual(full.payment_call['amount'], Decimal('80000.00'))

    def test_empty_invoice_has_no_bar(self):
        empty = Invoice.objects.create(client=self.client_obj, project_title='Draft')
        self.assertIsNone(empty.payment_call)
