# Generated by Django 5.2.9 on 2026-02-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kianvosite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text="E.g., '2025' or 'Q3 2026'", max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'year'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('current', 'Current Service'), ('future', 'Future Vision (Planned)')], default='current', help_text='Is this a current service or a future planned vision?', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='timeline_text',
            field=models.CharField(blank=True, help_text="E.g., '2026-2027' (only used for future vision services)", max_length=100),
        ),
    ]
