# Generated by Django 5.2.10 on 2026-05-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kianvosite', '0003_alter_blogpost_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(help_text="e.g., 'Director of Research & AI'", max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Short biography or description of their role')),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('icon_class', models.CharField(blank=True, help_text='Fallback icon if no image (FontAwesome class)', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
    ]
