# Generated by Django 5.2.10 on 2026-05-24 12:21

import ckeditor_uploader.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kianvosite', '0004_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('announcement_type', models.CharField(choices=[('bootcamp', 'Bootcamp'), ('training', 'Training Program'), ('session', 'Programming Session'), ('workshop', 'Workshop'), ('other', 'Other')], default='bootcamp', max_length=20)),
                ('short_description', models.CharField(help_text='Brief summary for listing cards', max_length=500)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(help_text='Full details about the programme')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='announcements/')),
                ('start_date', models.DateField(help_text='When the programme begins')),
                ('end_date', models.DateField(blank=True, help_text='When the programme ends', null=True)),
                ('application_deadline', models.DateField(help_text='Last date to accept applications')),
                ('venue', models.CharField(blank=True, help_text="Physical location or 'Online'", max_length=300)),
                ('mode', models.CharField(blank=True, help_text="e.g., 'In-Person', 'Online', 'Hybrid'", max_length=100)),
                ('fee', models.CharField(blank=True, help_text="e.g., 'Free', 'TZS 50,000', 'Contact us'", max_length=100)),
                ('capacity', models.IntegerField(default=0, help_text='0 for unlimited')),
                ('prerequisites', models.TextField(blank=True, help_text='Requirements for participants')),
                ('contact_email', models.EmailField(blank=True, help_text='Contact for this specific announcement', max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('collect_applications', models.BooleanField(default=True, help_text='Show application form on the announcement page')),
                ('application_fields', models.TextField(blank=True, help_text='Extra fields for application form (one per line, format: label|field_type|required). \nField types: text, email, phone, textarea, select:option1,option2. Default fields (name, email, phone, motivation) are always included.')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open for Applications'), ('closed', 'Closed'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon_class', models.CharField(blank=True, help_text='FontAwesome class', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Gallery Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='demo_password',
            field=models.CharField(blank=True, help_text='Demo login password', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='demo_username',
            field=models.CharField(blank=True, help_text='Demo login username', max_length=100),
        ),
        migrations.CreateModel(
            name='AnnouncementApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('motivation', models.TextField(help_text='Why they want to join')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Extra application fields data')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='kianvosite.announcement')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='gallery/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])])),
                ('event_date', models.DateField(blank=True, help_text='Date the event/training took place', null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='kianvosite.gallerycategory')),
            ],
            options={
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['-is_featured', 'order', '-event_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/screenshots/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])])),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_featured', models.BooleanField(default=False, help_text='Show as the main showcase image')),
                ('order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='kianvosite.project')),
            ],
            options={
                'verbose_name_plural': 'Product Screenshots',
                'ordering': ['-is_featured', 'order'],
            },
        ),
    ]
