# Generated by Django 5.2.10 on 2026-05-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kianvosite', '0005_announcement_gallerycategory_project_demo_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, help_text='Source code / GitHub link', null=True),
        ),
    ]
