# Generated by Django 5.2.10 on 2026-05-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kianvosite', '0006_project_github_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub profile URL', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='portfolio_url',
            field=models.URLField(blank=True, help_text='Personal portfolio or website URL', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter / X profile URL', null=True),
        ),
    ]
