# Generated by Django 5.2.10 on 2026-05-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kianvosite', '0007_teammember_github_url_teammember_linkedin_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(help_text='e.g., Facebook, Instagram, TikTok', max_length=50)),
                ('icon_class', models.CharField(help_text="FontAwesome icon class, e.g. 'fab fa-facebook-f'", max_length=100)),
                ('url', models.URLField(help_text='Full URL to the social media page')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'platform'],
            },
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='twitter_url',
        ),
    ]
