# Generated by Django 5.2.10 on 2026-05-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kianvosite', '0008_sociallink_remove_teammember_twitter_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.CharField(help_text='Brief tagline', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Full description (optional)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='active_products/')),
                ('icon_class', models.CharField(blank=True, help_text='Icon class for fallback display', max_length=100)),
                ('category', models.CharField(choices=[('edtech', 'Education Technology'), ('business', 'Business & Operations')], default='edtech', max_length=20)),
                ('is_featured', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main headline text', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Small label above title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Paragraph below title')),
                ('image', models.ImageField(blank=True, help_text='Banner illustration', null=True, upload_to='hero/')),
                ('cta_primary_text', models.CharField(default='Explore Our Work', max_length=100)),
                ('cta_primary_url', models.CharField(default='/services/', max_length=200)),
                ('cta_secondary_text', models.CharField(default='Get in Touch', max_length=100)),
                ('cta_secondary_url', models.CharField(default='/contact/', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
