# Generated by Django 5.2.10 on 2026-05-25 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kianvosite', '0009_activeproduct_heroslide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoadmapMilestone',
        ),
        migrations.AddField(
            model_name='activeproduct',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Link to Project detail page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_products', to='kianvosite.project'),
        ),
    ]
