# Generated by Django 5.2.10 on 2026-06-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kianvosite', '0010_delete_roadmapmilestone_activeproduct_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Meta description for Google (max 160 chars). Use target search phrases naturally.', max_length=160),
        ),
        migrations.AddField(
            model_name='project',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text="Comma-separated keywords. E.g. 'pharmacy management system, pharmacy software Tanzania, drug inventory system'", max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='seo_title',
            field=models.CharField(blank=True, help_text="Page title for Google (max 70 chars). E.g. 'IMFORIA – Best Pharmacy Management System in Tanzania | KianvoSoft'", max_length=70),
        ),
    ]
