# Generated by Django 5.2.10

from django.db import migrations, models


def seed_flagship_spotlight(apps, schema_editor):
    """Turn the spotlight reel on out of the box for the two systems the
    business actually leads with. Safe no-op if the slugs aren't present."""
    Project = apps.get_model('kianvosite', 'Project')
    for order, slug in enumerate(['imforia', 'mjenzi']):
        Project.objects.filter(slug=slug).update(is_spotlight=True, spotlight_order=order)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('kianvosite', '0011_add_project_seo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_spotlight',
            field=models.BooleanField(default=False, help_text="Feature this system in the animated 'Now Showcasing' reel at the very top of the homepage, above the hero banner. Keep this to your 2-4 most important systems — everything ticked here rotates like a movie-poster carousel."),
        ),
        migrations.AddField(
            model_name='project',
            name='spotlight_order',
            field=models.PositiveIntegerField(default=0, help_text='Order within the spotlight reel — lower shows first.'),
        ),
        migrations.RunPython(seed_flagship_spotlight, noop),
    ]
