# Generated by Django 5.2.10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kianvosite', '0012_project_spotlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='spotlight_image',
            field=models.ImageField(blank=True, help_text="Purpose-made poster art for the homepage 'Now Showcasing' reel (portrait or landscape both work — it's cropped to fill a wide poster frame). Falls back to the banner image, then the thumbnail, then on-brand generated art if left blank.", null=True, upload_to='projects/spotlight/'),
        ),
    ]
